# pyinfra test VM's

Vagrant.configure('2') do |config|
    config.ssh.insert_key = false
    config.ssh.private_key_path = 'files/insecure_private_key'

    # Disable /vagrant synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true

    # Set the boxes memory (8 boxes = 4G total)
    config.vm.provider 'virtualbox' do |v|
        v.memory = 512
    end

    # Disable updating/installing Virtualbox guest additions with vagrant-vbguest
    if Vagrant.has_plugin?('vagrant-vbguest')
        config.vbguest.auto_update = false
    end

    # Begin pyinfra test VM's:
    #

    config.vm.define :ubuntu14 do |ubuntu|
        ubuntu.vm.box = 'bento/ubuntu-14.04'
    end

    config.vm.define :ubuntu16 do |ubuntu|
        ubuntu.vm.box = 'bento/ubuntu-16.04'
    end

    config.vm.define :debian7 do |debian|
        debian.vm.box = 'bento/debian-7'
    end

    config.vm.define :debian8 do |debian|
        debian.vm.box = 'bento/debian-8'
    end

    config.vm.define :debian9 do |debian|
        debian.vm.box = 'bento/debian-9'
    end

    config.vm.define :centos6 do |centos|
        centos.vm.box = 'bento/centos-6'
    end

    config.vm.define :centos7 do |centos|
        centos.vm.box = 'bento/centos-7'
    end


    config.vm.define :openbsd58 do |openbsd|
        openbsd.vm.box = 'twingly/openbsd-5.8-amd64'
    end

    config.vm.define :fedora23 do |fedora|
        fedora.vm.box = 'boxcutter/fedora23'
    end
end
