# pyinfra test VM's

Vagrant.configure('2') do |config|
    config.ssh.insert_key = false
    config.ssh.private_key_path = 'files/insecure_private_key'

    config.vm.define :ubuntu14 do |ubuntu|
        ubuntu.vm.box = 'ubuntu/trusty64'
        ubuntu.vm.network :private_network, ip: '20.20.20.21'
    end

    config.vm.define :ubuntu15 do |ubuntu|
        ubuntu.vm.box = 'ubuntu/vivid64'
        ubuntu.vm.network :private_network, ip: '20.20.20.26'
    end

    config.vm.define :centos6 do |centos|
        centos.vm.box = 'chef/centos-6.6'
        centos.vm.network :private_network, ip: '20.20.20.22'
    end

    config.vm.define :centos7 do |centos|
        centos.vm.box = 'chef/centos-7.0'
        centos.vm.network :private_network, ip: '20.20.20.23'
    end

    config.vm.define :debian7 do |debian|
        debian.vm.box = 'chef/debian-7.7'
        debian.vm.network :private_network, ip: '20.20.20.24'
    end

    config.vm.define :openbsd57 do |openbsd|
        openbsd.vm.box = 'tmatilai/openbsd-5.7'
        openbsd.vm.network :private_network, ip: '20.20.20.25'
    end
end
