"""
Manage BSD packages and repositories. Note that BSD package names are case-sensitive.
"""

from __future__ import annotations

from pyinfra import host
from pyinfra.api import operation
from pyinfra.facts.files import File
from pyinfra.facts.pkg import PkgPackages
from pyinfra.facts.server import Arch, Os, OsVersion, Which
from pyinfra.facts.util.packages import PackageStatus

from .util.packaging import ensure_packages


@operation(is_idempotent=False)
def update(force: bool = False):
    """
    Update the local pkg repository catalogues (FreeBSD ``pkg`` only).

    + force: force a full download of the repository catalogues
    """

    yield "pkg update -f" if force else "pkg update"


@operation()
def upgrade():
    """
    Upgrade all pkg packages with an available upgrade (FreeBSD ``pkg`` only).

    Noops when no installed package has an upgrade available.

    **Example:**

    .. code:: python

        from pyinfra.operations import pkg
        pkg.upgrade(
            name="Upgrade all pkg packages",
        )

    """

    if not any(
        package.status is PackageStatus.UPGRADEABLE for package in host.get_fact(PkgPackages)
    ):
        host.noop("all packages are up to date")
        return

    yield "pkg upgrade -y"


@operation()
def packages(
    packages: str | list[str] | None = None,
    present: bool = True,
    latest: bool = False,
    pkg_path: str | None = None,
):
    """
    Install/remove/update pkg packages. This will use ``pkg ...`` where available
    (FreeBSD) and the ``pkg_*`` variants elsewhere.

    + packages: list of packages to ensure
    + present: whether the packages should be installed
    + latest: upgrade installed packages with an available upgrade (FreeBSD ``pkg`` only)
    + pkg_path: the PKG_PATH environment variable to set

    Packages locked with ``pkg lock`` always noop, even with ``latest=True``.

    pkg_path:
        By default this is autogenerated as follows (tested/working for OpenBSD):
        ``http://ftp.<OS>.org/pub/<OS>/<VERSION>/packages/<ARCH>/``. Note that OpenBSD's
        official mirrors only hold the latest two versions packages.

        NetBSD/FreeBSD helpfully use their own directory structures, so the default won't
        work.

    **Example:**

    .. code:: python

        from pyinfra.operations import pkg
        pkg.packages(
            name="Install Vim and Vim Addon Manager",
            packages=["vim-addon-manager", "vim"],
        )

    """

    if present is True:
        if not pkg_path and not host.get_fact(File, path="/etc/installurl"):
            host_os = host.get_fact(Os) or ""
            pkg_path = f"http://ftp.{host_os.lower()}.org/pub/{host_os}/{host.get_fact(OsVersion)}/packages/{host.get_fact(Arch)}/"

    # FreeBSD used "pkg ..." and OpenBSD uses "pkg_[add|delete]"
    is_pkg = host.get_fact(Which, command="pkg")
    install_command = "pkg install -y" if is_pkg else "pkg_add"
    uninstall_command = "pkg delete -y" if is_pkg else "pkg_delete"

    if pkg_path:
        install_command = f"PKG_PATH={pkg_path} {install_command}"

    current_packages = host.get_fact(PkgPackages)

    yield from ensure_packages(
        host,
        packages,
        # list() so the FakeFact list wrapper used in tests also normalizes
        list(current_packages),
        present,
        install_command=install_command,
        uninstall_command=uninstall_command,
        latest=latest,
        upgrade_command="pkg upgrade -y" if is_pkg else None,
    )
