def download(
    src,
    dest,
    user=None,
    group=None,
    mode=None,
    cache_time=None,
    force=False,
    sha256sum=None,
    sha1sum=None,
    md5sum=None,
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...

def line(
    path,
    line,
    present=True,
    replace=None,
    flags=None,
    backup=False,
    interpolate_variables=False,
    escape_regex_characters=False,
    assume_present=False,
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...

def replace(
    path,
    text=None,
    replace=None,
    flags=None,
    backup=False,
    interpolate_variables=False,
    match=None,  # deprecated
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...

def sync(
    src,
    dest,
    user=None,
    group=None,
    mode=None,
    delete=False,
    exclude=None,
    exclude_dir=None,
    add_deploy_dir=True,
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...

def rsync(src, dest, flags=["-ax", "--delete"], _sudo = None, _sudo_user = None, _use_sudo_login = None, _use_sudo_password = None, _preserve_sudo_env = None, _su_user = None, _use_su_login = None, _preserve_su_env = None, _su_shell = None, _doas = None, _doas_user = None, _shell_executable = None, _chdir = None, _env = None, _success_exit_codes = None, _timeout = None, _get_pty = None, _stdin = None, name = None, _ignore_errors = None, _precondition = None, _postcondition = None, _on_success = None, _on_error = None, _parallel = None, _run_once = None, _serial = None):...

def get(
    src,
    dest,
    add_deploy_dir=True,
    create_local_dir=False,
    force=False,
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...

def put(
    src,
    dest,
    user=None,
    group=None,
    mode=None,
    add_deploy_dir=True,
    create_remote_dir=True,
    force=False,
    assume_exists=False,
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...

def template(src, dest, user=None, group=None, mode=None, create_remote_dir=True, _sudo = None, _sudo_user = None, _use_sudo_login = None, _use_sudo_password = None, _preserve_sudo_env = None, _su_user = None, _use_su_login = None, _preserve_su_env = None, _su_shell = None, _doas = None, _doas_user = None, _shell_executable = None, _chdir = None, _env = None, _success_exit_codes = None, _timeout = None, _get_pty = None, _stdin = None, name = None, _ignore_errors = None, _precondition = None, _postcondition = None, _on_success = None, _on_error = None, _parallel = None, _run_once = None, _serial = None, **data):...

def link(
    path,
    target=None,
    present=True,
    assume_present=False,
    user=None,
    group=None,
    symbolic=True,
    create_remote_dir=True,
    force=False,
    force_backup=True,
    force_backup_dir=None,
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...

def file(
    path,
    present=True,
    assume_present=False,
    user=None,
    group=None,
    mode=None,
    touch=False,
    create_remote_dir=True,
    force=False,
    force_backup=True,
    force_backup_dir=None,
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...

def directory(
    path,
    present=True,
    assume_present=False,
    user=None,
    group=None,
    mode=None,
    recursive=False,
    force=False,
    force_backup=True,
    force_backup_dir=None,
    _no_check_owner_mode=False,
    _no_fail_on_link=False,
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...