def chain(
    chain,
    present=True,
    table="filter",
    policy=None,
    version=4,
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...

def rule(
    chain,
    jump,
    present=True,
    table="filter",
    append=True,
    version=4,
    # Core iptables filter arguments
    protocol=None,
    not_protocol=None,
    source=None,
    not_source=None,
    destination=None,
    not_destination=None,
    in_interface=None,
    not_in_interface=None,
    out_interface=None,
    not_out_interface=None,
    # After-rule arguments
    to_destination=None,
    to_source=None,
    to_ports=None,
    log_prefix=None,
    # Extras and extra shortcuts
    destination_port=None,
    source_port=None,
    extras="",
    _sudo = None,
    _sudo_user = None,
    _use_sudo_login = None,
    _use_sudo_password = None,
    _preserve_sudo_env = None,
    _su_user = None,
    _use_su_login = None,
    _preserve_su_env = None,
    _su_shell = None,
    _doas = None,
    _doas_user = None,
    _shell_executable = None,
    _chdir = None,
    _env = None,
    _success_exit_codes = None,
    _timeout = None,
    _get_pty = None,
    _stdin = None,
    name = None,
    _ignore_errors = None,
    _precondition = None,
    _postcondition = None,
    _on_success = None,
    _on_error = None,
    _parallel = None,
    _run_once = None,
    _serial = None,
):...