# pyinfra test vm

Vagrant.configure('2') do |config|
    # Disable /vagrant synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.provider 'virtualbox' do |v|
        v.memory = 256
    end

    # Disable updating/installing Virtualbox guest additions with vagrant-vbguest
    if Vagrant.has_plugin?('vagrant-vbguest')
        config.vbguest.auto_update = false
    end

    config.vm.define :one do |ubuntu|
        ubuntu.vm.box = 'bento/ubuntu-18.04'
        ubuntu.vm.provider 'virtualbox' do |v|
            v.memory = 384  # ubuntu18 is memory hungry
        end
    end

    config.vm.define :two do |ubuntu|
        ubuntu.vm.box = 'bento/ubuntu-18.04'
        ubuntu.vm.provider 'virtualbox' do |v|
            v.memory = 384  # ubuntu18 is memory hungry
        end
    end

end
