# pyinfra test vm

Vagrant.configure('2') do |config|
    # Disable /vagrant synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.provider 'virtualbox' do |v|
        v.memory = 256
    end

    # puppet master wants at least 1gb of ram
    config.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "2"
    end

    # Disable updating/installing Virtualbox guest additions with vagrant-vbguest
    if Vagrant.has_plugin?('vagrant-vbguest')
        config.vbguest.auto_update = false
    end

    config.vm.define :master do |centos|
        centos.vm.box = 'bento/centos-8'
    end

    config.vm.define :agent do |centos|
        centos.vm.box = 'bento/centos-8'
    end

end
